// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

type Gem struct {
	UserID     int64
	GuildID    int64
	Diamond    int32
	Sunstone   int32
	Citrine    int32
	Topaz      int32
	Peridot    int32
	Jade       int32
	Aquamarine int32
	Sapphire   int32
	Amethyst   int32
	Kunzite    int32
	Ruby       int32
	Garnet     int32
	Painite    int32
}

type Item struct {
	UserID  int64
	GuildID int64
	Item    string
}

type Profile struct {
	UserID               int64
	GuildID              int64
	Networth             int64
	DiamondMultiplier    float64
	SunstoneMultiplier   float64
	CitrineMultiplier    float64
	TopazMultiplier      float64
	PeridotMultiplier    float64
	JadeMultiplier       float64
	AquamarineMultiplier float64
	SapphireMultiplier   float64
	AmethystMultiplier   float64
	KunziteMultiplier    float64
	RubyMultiplier       float64
	GarnetMultiplier     float64
	PainiteMultiplier    float64
}
