// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

type Gem struct {
	UserID     int64
	GuildID    int64
	Diamond    int32
	Sunstone   int32
	Citrine    int32
	Topaz      int32
	Peridot    int32
	Jade       int32
	Aquamarine int32
	Sapphire   int32
	Amethyst   int32
	Kunzite    int32
	Ruby       int32
	Garnet     int32
	Painite    int32
}
